"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 16:31:54.008009
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=True),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)

    op.create_table('hazard_library_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('risk_matrix_image_sha256', sa.String(length=64), nullable=True),
    sa.Column('header_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('hospital_network_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hazard_library_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_hazard_library_versions_version'))
    )
    op.create_table('journey_code_sequences',
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('state_code', name=op.f('pk_journey_code_sequences'))
    )
    op.create_table('route_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_route_cache'))
    )
    op.create_table('uploaded_csvs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('csv_path', sa.String(length=500), nullable=False),
    sa.Column('csv_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_csvs'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth_subject', name=op.f('uq_users_auth_subject')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('bulk_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('csv_path', sa.String(length=500), nullable=False),
    sa.Column('csv_sha256', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('llm_mode', sa.String(length=10), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('analysed', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('anthropic_batch_id', sa.String(length=120), nullable=True),
    sa.Column('zip_path', sa.String(length=500), nullable=True),
    sa.Column('manifest_csv_path', sa.String(length=500), nullable=True),
    sa.Column('manifest_xlsx_path', sa.String(length=500), nullable=True),
    sa.Column('summary_json_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_bulk_jobs_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_jobs'))
    )
    with op.batch_alter_table('bulk_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_jobs_csv_sha256'), ['csv_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_jobs_idempotency_key'), ['idempotency_key'], unique=False)

    op.create_table('hazards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('library_version_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('sr_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('probability', sa.String(length=1), nullable=False),
    sa.Column('rpn_code', sa.String(length=4), nullable=False),
    sa.Column('severity_band', sa.String(length=10), nullable=False),
    sa.Column('matrix_zone', sa.String(length=10), nullable=False),
    sa.Column('control_2w_raw', sa.Text(), nullable=False),
    sa.Column('control_4w_raw', sa.Text(), nullable=False),
    sa.Column('control_2w_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('control_4w_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('control_short_2w', sa.Text(), nullable=True),
    sa.Column('control_short_4w', sa.Text(), nullable=True),
    sa.Column('detection_profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['library_version_id'], ['hazard_library_versions.id'], name=op.f('fk_hazards_library_version_id_hazard_library_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hazards')),
    sa.UniqueConstraint('library_version_id', 'code', name=op.f('uq_hazards_library_version_id'))
    )
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hazards_library_version_id'), ['library_version_id'], unique=False)

    op.create_table('journeys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_code', sa.String(length=40), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('bulk_job_item_id', sa.Uuid(), nullable=True),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('vehicle_type', sa.String(length=4), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('depart_time', sa.String(length=5), nullable=True),
    sa.Column('manager_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True),
    sa.Column('nearest_hospital', sa.String(length=300), nullable=True),
    sa.Column('nearest_police', sa.String(length=300), nullable=True),
    sa.Column('is_round_trip', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_journeys_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journeys')),
    sa.UniqueConstraint('journey_code', name=op.f('uq_journeys_journey_code'))
    )
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journeys_bulk_job_item_id'), ['bulk_job_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journeys_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_journeys_input_hash'), ['input_hash'], unique=False)

    op.create_table('risk_matrix_cells',
    sa.Column('library_version_id', sa.Uuid(), nullable=False),
    sa.Column('probability', sa.String(length=1), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['library_version_id'], ['hazard_library_versions.id'], name=op.f('fk_risk_matrix_cells_library_version_id_hazard_library_versions')),
    sa.PrimaryKeyConstraint('library_version_id', 'probability', 'severity', name=op.f('pk_risk_matrix_cells'))
    )
    op.create_table('bulk_job_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bulk_job_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('route_ref', sa.String(length=100), nullable=False),
    sa.Column('raw_row', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('normalized_input', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=True),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('counted', sa.Boolean(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bulk_job_id'], ['bulk_jobs.id'], name=op.f('fk_bulk_job_items_bulk_job_id_bulk_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_job_items')),
    sa.UniqueConstraint('bulk_job_id', 'row_number', name=op.f('uq_bulk_job_items_bulk_job_id'))
    )
    with op.batch_alter_table('bulk_job_items', schema=None) as batch_op:
        batch_op.create_index('ix_bulk_job_items_job_status', ['bulk_job_id', 'status'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('bulk_job_item_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('narrative_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('report_facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_generation_jobs_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs'))
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_bulk_job_item_id'), ['bulk_job_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_journey_id'), ['journey_id'], unique=False)
        batch_op.create_index('ix_generation_jobs_status_queued', ['status', 'queued_at'], unique=False)

    op.create_table('jmp_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('document_code', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('route_name', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('decision', sa.String(length=40), nullable=True),
    sa.Column('journey_score', sa.Integer(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('report_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('narrative_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('template_version', sa.String(length=20), nullable=False),
    sa.Column('hazard_library_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('scoring_version', sa.String(length=20), nullable=False),
    sa.Column('rules_version', sa.String(length=20), nullable=False),
    sa.Column('app_version', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('narrative_source', sa.String(length=20), nullable=False),
    sa.Column('providers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('html_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('pdf_bytes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('render_ms', sa.Integer(), nullable=True),
    sa.Column('pdf_ms', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_jmp_documents_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jmp_documents'))
    )
    with op.batch_alter_table('jmp_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jmp_documents_document_code'), ['document_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_jmp_documents_journey_id'), ['journey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jmp_documents_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_jmp_documents_risk_level'), ['risk_level'], unique=False)

    op.create_table('journey_hazards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('hazard_id', sa.Uuid(), nullable=False),
    sa.Column('applicable', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.String(length=10), nullable=True),
    sa.Column('display_band', sa.String(length=10), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('locations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('narrative_context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], name=op.f('fk_journey_hazards_hazard_id_hazards')),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_journey_hazards_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journey_hazards')),
    sa.UniqueConstraint('journey_id', 'hazard_id', name=op.f('uq_journey_hazards_journey_id'))
    )
    with op.batch_alter_table('journey_hazards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journey_hazards_journey_id'), ['journey_id'], unique=False)

    op.create_table('journey_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scoring_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_journey_scores_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journey_scores')),
    sa.UniqueConstraint('journey_id', 'dimension', name=op.f('uq_journey_scores_journey_id'))
    )
    with op.batch_alter_table('journey_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journey_scores_journey_id'), ['journey_id'], unique=False)

    op.create_table('journey_stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('raw_text', sa.String(length=300), nullable=False),
    sa.Column('geocoded_name', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('admin_area', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('place_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('geocode_confidence', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_journey_stops_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journey_stops')),
    sa.UniqueConstraint('journey_id', 'seq', name=op.f('uq_journey_stops_journey_id'))
    )
    with op.batch_alter_table('journey_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journey_stops_journey_id'), ['journey_id'], unique=False)

    op.create_table('route_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journey_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_request_id', sa.String(length=120), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('distance_range', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('duration_range', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('geometry', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('legs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('segments', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('road_type_split', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('exposures', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('alternatives', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('elevation_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rules_version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_route_analysis_journey_id_journeys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_analysis')),
    sa.UniqueConstraint('journey_id', name=op.f('uq_route_analysis_journey_id'))
    )
    op.create_table('generation_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('journey_id', sa.Uuid(), nullable=True),
    sa.Column('bulk_job_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('service_tier', sa.String(length=20), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('static_prefix_sha256', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_5m_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_1h_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('estimated_cost_inr', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('stop_reason', sa.String(length=30), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], name=op.f('fk_generation_usage_generation_job_id_generation_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_usage'))
    )
    with op.batch_alter_table('generation_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_usage_bulk_job_id'), ['bulk_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_usage_generation_job_id'), ['generation_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_usage_journey_id'), ['journey_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_usage_journey_id'))
        batch_op.drop_index(batch_op.f('ix_generation_usage_generation_job_id'))
        batch_op.drop_index(batch_op.f('ix_generation_usage_created_at'))
        batch_op.drop_index(batch_op.f('ix_generation_usage_bulk_job_id'))

    op.drop_table('generation_usage')
    op.drop_table('route_analysis')
    with op.batch_alter_table('journey_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journey_stops_journey_id'))

    op.drop_table('journey_stops')
    with op.batch_alter_table('journey_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journey_scores_journey_id'))

    op.drop_table('journey_scores')
    with op.batch_alter_table('journey_hazards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journey_hazards_journey_id'))

    op.drop_table('journey_hazards')
    with op.batch_alter_table('jmp_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jmp_documents_risk_level'))
        batch_op.drop_index(batch_op.f('ix_jmp_documents_region'))
        batch_op.drop_index(batch_op.f('ix_jmp_documents_journey_id'))
        batch_op.drop_index(batch_op.f('ix_jmp_documents_document_code'))

    op.drop_table('jmp_documents')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_jobs_status_queued')
        batch_op.drop_index(batch_op.f('ix_generation_jobs_journey_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_bulk_job_item_id'))

    op.drop_table('generation_jobs')
    with op.batch_alter_table('bulk_job_items', schema=None) as batch_op:
        batch_op.drop_index('ix_bulk_job_items_job_status')

    op.drop_table('bulk_job_items')
    op.drop_table('risk_matrix_cells')
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journeys_input_hash'))
        batch_op.drop_index(batch_op.f('ix_journeys_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_journeys_bulk_job_item_id'))

    op.drop_table('journeys')
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hazards_library_version_id'))

    op.drop_table('hazards')
    with op.batch_alter_table('bulk_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_jobs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_bulk_jobs_csv_sha256'))

    op.drop_table('bulk_jobs')
    op.drop_table('users')
    op.drop_table('uploaded_csvs')
    op.drop_table('route_cache')
    op.drop_table('journey_code_sequences')
    op.drop_table('hazard_library_versions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
